version: '3'
services:
  bot:
    build: src/
    entrypoint: python -u /app/main.py
    volumes:
      - "./mandrake.conf:/app/mandrake.conf:ro"
      - "./src:/app"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:alpine
    volumes:
    - "db_data:/var/lib/postgresql/data"
    restart: always

volumes:
  db_data: